### ISSUE TITLE
VM synthesis Delay Problem

### ISSUE THREAD

**Issue by skcs** [cmusatyalab/elijah-cloudlet#33]
Sir,
Following the steps at Elijah Provisioning, we imported the base VM Ubuntu12.04 32 bit. After making the customizations to it ( loading libraries like OpenCV etc , Apache Tomcat Server, and the server code for Face Recognition) when we close the VNC, the cloudlet code starts to create VM Overlay. Using the overlay when we try to synthesize the launch VM the process starts and then stops at "INFO start monitoring at /tmp/cloudlet-xxx/qemu-trim-log". It does not open the launch VM even after waiting for an hour.
Please note that, we are otherwise able to get the launch VMs with light weight programs. This is only happening when we do lots of customizations for our Face Recognition code.The overlay.zip file is 878MB. Can you please explain how to solve this issue?
Kindly, help us!

**Comment by krha** [comment]
Hi @skcs 

Sorry for being a bit late. Given that the overlay size is really big (878MB), I guess there might be a resource scarce issue (e.g. memory thrashing) depending on your machine specification. Could you check CPU usage and memory usage when you do VM synthesis with that big VM overlay? Thanks.

**Comment by skcs** [comment]
Thanks Sir!
As you have pointed out the issue was with the RAM size of the PC. Though it wasnt working on a PC with 4GB RAM, I am able to successfully create the overlay and launch the VM on a PC with 8GB RAM.
Thanks again!
